---
- name: Install packages
  become: true
  block:
    - name: Install Chrome repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Sublime repo
      ansible.builtin.apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present

    - name: Install Sublime repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://repo.skype.com/deb stable main
        state: present

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - google-chrome-stable
          - sublime-text
          - sublime-merge
          - skypeforlinux
          - nvidia-driver
          - mdadm

          - x11vnc

- name: Configure mdadm
  become: true
  ansible.builtin.copy:
    src: files/mdadm.conf
    dest: /etc/mdadm/mdadm.conf
    owner: root
    group: root
    mode: '0700'

- name: Add mount-nas alias
  lineinfile:
    path: '~/.bashrc'
    line: "alias mount-nas='sudo mount /dev/md1p1 /mnt/nas'"

# Need to share desktop
- name: Configure x11vnc service
  become: true
  ansible.builtin.copy:
    src: files/x11vnc.service
    dest: /etc/systemd/system/x11vnc.service
    owner: root
    group: root
    mode: '0700'
