---
- name: Debug
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Common init tasks
      import_role:
        name: common
        tasks_from: init

    - name: Import home role
      import_role:
        name: home
 
     - name: Import common role
      import_role:
        name: common


